services:
  # Сервис для базы данных
  db:
    container_name: UserBalanceDB
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BankDB
    
    ports: 
      - "5434:5432"  # Пробрасываем порт 5433 на хосте к 5432 в контейнере
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Сервис для вашего приложения
  app:
    container_name: BankAPI
    build:
      context: .  # Путь к папке с Dockerfile приложения
    ports:
      - "8444:8443"  # Пробрасываем порт 8443 с контейнера на хост
    depends_on:
      - db  # Указываем, что приложение зависит от базы данных
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/BankDB  # Используем имя сервиса db вместо localhost
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
