spring: 
  application:
    name: BankAPI
  mvc:
    log-request-details: true
  datasource: 
      url: jdbc:postgresql://localhost:5434/BankDB
      hikari:
          username: postgres
          password: postgres

  jpa:
      hibernate:
          ddl-auto: create
      properties:
          dialect: org.hibernate.dialect.PostgreSQLDialect


server:
    port: 8444


logging:
  level:
    org.springframework.web: DEBUG       # Логирование Spring MVC
    org.springframework.security: DEBUG  # Логирование Spring Security
    com.bank.bankservice: DEBUG          # Логирование вашего приложения
    org.hibernate.SQL: DEBUG             # Логирование SQL-запросов
    org.hibernate.type: TRACE  
